### PR TITLE
Make "ESC" key to function as BACK

### PR DESCRIPTION
**Pull request by ilhan-athn7**

### CODE REVIEW

**Comment by utzcoz** [comment]
I think it's better to convert ESC to BACK in frameworks/base when focus app doesn't support ESC key. cc @electrikjesus

**Comment by utzcoz** [comment]
@ilhan-athn7 Looks like I misunderstood KCM file. Does fallback means the ESC will behave likes BACK if focused app doesn't process it?

**Comment by ilhan-athn7** [comment]
@utzcoz Yes,

Since Android 9, ESC key is handled by foreground/focused app, which makes it non-functional on most case.

For example, when you press ESC key while you are in settings app, nothing happens, because settings does not handle/processes ESC key.

**Comment by utzcoz** [comment]
@ilhan-athn7 Cool. I think it needs @hmtheboy154 and @electrikjesus 's reviewing and  approving to merge it.

**Comment by hmtheboy154** [comment]
I'll merge into r11-x86 instead, thanks

**Pull request closed without merging**
